# -*- coding: utf-8 -*-
"""Anomaly Detection Robbery

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nal3tdm_jXlFYDgGhUFX3o0YfjLfyLfk
"""

!pip install kagglehub -q

import kagglehub

path = kagglehub.dataset_download("simonphall/ucf-crime-images")
print("Raw dataset path:", path)

import os

root_dir = path  # "/kaggle/input/ucf-crime-images"
print("root:", root_dir, os.listdir(root_dir))

# First level: ['image_category_captions.csv', 'UCF Image Dataset']
level1 = os.path.join(root_dir, "UCF Image Dataset")
print("level1:", level1, os.listdir(level1))

# Second level: real folder containing PNGs (also called 'UCF Image Dataset')
images_dir = os.path.join(level1, "UCF Image Dataset")
print("images_dir:", images_dir, os.listdir(images_dir)[:10])

from PIL import Image
import matplotlib.pyplot as plt
import os

sample_path = os.path.join(images_dir, os.listdir(images_dir)[0])
print("Sample path:", sample_path)

img = Image.open(sample_path).convert("RGB")
plt.imshow(img)
plt.axis("off")

import pandas as pd
import os

# The 'path' variable (root_dir) is available from previous cells: '/kaggle/input/ucf-crime-images'
# The 'images_dir' variable is available from previous cells: '/kaggle/input/ucf-crime-images/UCF Image Dataset/UCF Image Dataset'

# Load the image category captions CSV
csv_path = os.path.join(root_dir, "image_category_captions.csv")
df = pd.read_csv(csv_path)

# Assuming the CSV has columns named 'image_name' and 'category'
# Filter for 'Normal' and 'Burglary' categories
normal_df = df[df["category"] == "Normal"]
burglary_df = df[df["category"] == "Burglary"]

# Example, when building paths from the CSV
normal_paths   = [os.path.join(images_dir, n) for n in normal_df["image_name"]]
burglary_paths = [os.path.join(images_dir, n) for n in burglary_df["image_name"]]

import pandas as pd
import os

csv_path = os.path.join(root_dir, "image_category_captions.csv")
df = pd.read_csv(csv_path)

print(df["category"].value_counts())  # just to inspect

# Treat all non‑burglary crimes as "normal" for this toy anomaly setup
normal_df = df[df["category"] != "Burglary"]
burglary_df = df[df["category"] == "Burglary"]

print(len(normal_df), "normal images")
print(len(burglary_df), "burglary images")

normal_paths   = [os.path.join(images_dir, n) for n in normal_df["image_name"]]
burglary_paths = [os.path.join(images_dir, n) for n in burglary_df["image_name"]]

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

class CrimeImageDataset(Dataset):
    def __init__(self, img_paths, transform=None):
        self.img_paths = img_paths
        self.transform = transform

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        img = Image.open(self.img_paths[idx]).convert("RGB")
        if self.transform:
            img = self.transform(img)
        return img

train_dataset = CrimeImageDataset(normal_paths, transform=transform)
test_dataset  = CrimeImageDataset(burglary_paths, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader  = DataLoader(test_dataset, batch_size=16, shuffle=False)

print("Train size:", len(train_dataset), "Test size:", len(test_dataset))

import torch.nn as nn

class SmallAE(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Conv2d(3, 16, 3, stride=2, padding=1),
            nn.ReLU(),
            nn.Conv2d(16, 32, 3, stride=2, padding=1),
            nn.ReLU(),
            nn.Conv2d(32, 64, 3, stride=2, padding=1),
            nn.ReLU()
        )
        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(64, 32, 3, stride=2, padding=1, output_padding=1),
            nn.ReLU(),
            nn.ConvTranspose2d(32, 16, 3, stride=2, padding=1, output_padding=1),
            nn.ReLU(),
            nn.ConvTranspose2d(16, 3, 3, stride=2, padding=1, output_padding=1),
            nn.Sigmoid()
        )

    def forward(self, x):
        z = self.encoder(x)
        out = self.decoder(z)
        return out

device = "cuda" if torch.cuda.is_available() else "cpu"
model = SmallAE().to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

epochs = 40
model.train()
for ep in range(epochs):
    total_loss = 0.0
    for batch in train_loader:
        batch = batch.to(device)
        recon = model(batch)
        loss = criterion(recon, batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * batch.size(0)
    print(f"Epoch {ep+1}/{epochs}, loss={total_loss/len(train_dataset):.6f}")

import numpy as np

model.eval()
anomaly_scores = []

with torch.no_grad():
    for batch in test_loader:
        batch = batch.to(device)
        recon = model(batch)
        mse = torch.mean((batch - recon) ** 2, dim=[1,2,3])
        anomaly_scores.extend(mse.cpu().numpy())

anomaly_scores = np.array(anomaly_scores)
print("Burglary scores:", anomaly_scores)

# Rank burglary images by anomaly score (high → more anomalous)
sorted_idx = np.argsort(-anomaly_scores)  # descending
print("Sorted scores (high→low):")
for i in sorted_idx:
    print(i, anomaly_scores[i])

import matplotlib.pyplot as plt

model.eval()
batch = next(iter(test_loader))
batch = batch.to(device)

with torch.no_grad():
    recon = model(batch)

batch = batch.cpu()
recon = recon.cpu()

n = min(4, batch.size(0))
for i in range(n):
    fig, axs = plt.subplots(1, 2, figsize=(6, 3))
    axs[0].imshow(batch[i].permute(1, 2, 0))
    axs[0].set_title(f"Original {i}")
    axs[0].axis("off")

    axs[1].imshow(recon[i].permute(1, 2, 0))
    axs[1].set_title(f"Reconstruction {i}")
    axs[1].axis("off")

    plt.show()

# Simple mixed test set: 20 normal + all burglary (adjust counts if needed)
mixed_paths = normal_paths[:20] + burglary_paths
mixed_labels = [0]*len(normal_paths[:20]) + [1]*len(burglary_paths)  # 0=normal, 1=burglary

mixed_dataset = CrimeImageDataset(mixed_paths, transform=transform)
mixed_loader  = DataLoader(mixed_dataset, batch_size=16, shuffle=False)

scores = []
with torch.no_grad():
    for batch in mixed_loader:
        batch = batch.to(device)
        recon = model(batch)
        mse = torch.mean((batch - recon) ** 2, dim=[1,2,3])
        scores.extend(mse.cpu().numpy())

scores = np.array(scores)
labels = np.array(mixed_labels)

# Example threshold: 90th percentile of all scores
thr = np.percentile(scores, 90)
preds = (scores > thr).astype(int)

print("Threshold:", thr)
print("Predicted anomalies:", preds)
print("True labels      :", labels)
print("Correct:", (preds == labels).sum(), "/", len(labels))

import matplotlib.pyplot as plt
import torch

model.eval()

# Get one batch of burglary images
batch = next(iter(test_loader))
batch = batch.to(device)

with torch.no_grad():
    recon = model(batch)

batch = batch.cpu()
recon = recon.cpu()

n = min(4, batch.size(0))  # show up to 4
for i in range(n):
    orig_img = batch[i].permute(1, 2, 0)
    recon_img = recon[i].permute(1, 2, 0)
    err_map = (orig_img - recon_img).pow(2).mean(dim=2)  # HxW error

    fig, axs = plt.subplots(1, 3, figsize=(9, 3))

    axs[0].imshow(orig_img)
    axs[0].set_title("Original")
    axs[0].axis("off")

    axs[1].imshow(recon_img)
    axs[1].set_title("Reconstruction")
    axs[1].axis("off")

    im = axs[2].imshow(err_map, cmap="hot")
    axs[2].set_title("Error heatmap")
    axs[2].axis("off")

    fig.colorbar(im, ax=axs[2], fraction=0.046, pad=0.04)
    plt.tight_layout()
    plt.show()

"""This gives you, for several burglary images:

left: original burglary frame

middle: what the autoencoder thinks a “normal” version looks like

right: heatmap showing where the model struggles (potential anomaly regions)
"""

import torch
import numpy as np

model.eval()
criterion = torch.nn.MSELoss(reduction="none")

batch = next(iter(test_loader))  # burglary batch
batch = batch.to(device)

with torch.no_grad():
    recon = model(batch)
    # per-image MSE
    per_img_mse = criterion(recon, batch).mean(dim=[1,2,3]).cpu().numpy()

threshold = np.percentile(per_img_mse, 90)  # or your chosen threshold
print("Scores:", per_img_mse)
print("Threshold:", threshold)

import matplotlib.pyplot as plt

batch_cpu = batch.cpu()
recon_cpu = recon.cpu()

n = min(4, batch_cpu.size(0))
for i in range(n):
    orig_img = batch_cpu[i].permute(1, 2, 0)
    recon_img = recon_cpu[i].permute(1, 2, 0)
    err_map = (orig_img - recon_img).pow(2).mean(dim=2)

    score = per_img_mse[i]
    is_anom = score > threshold
    label = f"Anomaly: {is_anom} (score={score:.4f})"

    fig, axs = plt.subplots(1, 3, figsize=(10, 3))

    axs[0].imshow(orig_img)
    axs[0].set_title("Original\n" + label)
    axs[0].axis("off")

    axs[1].imshow(recon_img)
    axs[1].set_title("Reconstruction")
    axs[1].axis("off")

    im = axs[2].imshow(err_map, cmap="hot")
    axs[2].set_title("Error heatmap")
    axs[2].axis("off")

    fig.colorbar(im, ax=axs[2], fraction=0.046, pad=0.04)
    plt.tight_layout()
    plt.show()

import torch
import numpy as np

model.eval()
criterion = torch.nn.MSELoss(reduction="none")

batch = next(iter(test_loader))  # burglary batch
batch = batch.to(device)

with torch.no_grad():
    recon = model(batch)
    # per-image MSE
    per_img_mse = criterion(recon, batch).mean(dim=[1,2,3]).cpu().numpy()

threshold = np.percentile(per_img_mse, 90)  # or your chosen threshold
print("Scores:", per_img_mse)
print("Threshold:", threshold)

import cv2
import numpy as np
import matplotlib.pyplot as plt
import torch

model.eval()
batch = next(iter(test_loader)).to(device)

with torch.no_grad():
    recon = model(batch)

batch_cpu = batch.cpu()
recon_cpu = recon.cpu()

n = min(4, batch_cpu.size(0))
for i in range(n):
    orig = batch_cpu[i].permute(1, 2, 0).numpy()
    recon_img = recon_cpu[i].permute(1, 2, 0).numpy()

    # Per-pixel squared error → anomaly map (H×W)
    err_map = ((orig - recon_img) ** 2).mean(axis=2)
    err_norm = (err_map - err_map.min()) / (err_map.max() - err_map.min() + 1e-8)

    # Convert to 0–255 and apply color map
    heat = np.uint8(255 * err_norm)
    heat_color = cv2.applyColorMap(heat, cv2.COLORMAP_JET)          # BGR
    orig_bgr = cv2.cvtColor((orig * 255).astype(np.uint8), cv2.COLOR_RGB2BGR)

    # Overlay: 0.6 heatmap + 0.4 original
    overlay = cv2.addWeighted(orig_bgr, 0.4, heat_color, 0.6, 0)
    overlay_rgb = cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(6,3))
    plt.subplot(1,2,1)
    plt.imshow(orig)
    plt.title("Original")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(overlay_rgb)
    plt.title("Suspicious regions (red/yellow)")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

# After computing heat (0–255)
    _, thresh = cv2.threshold(heat, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:
        c = max(contours, key=cv2.contourArea)
        x, y, w, h = cv2.boundingRect(c)
        cv2.rectangle(overlay_rgb, (x, y), (x+w, y+h), (0, 255, 0), 2)  # green box

    plt.figure(figsize=(3,3))
    plt.imshow(overlay_rgb)
    plt.title("Anomaly region")
    plt.axis("off")
    plt.show()

